/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FootballTrainerIndexImport } from './routes/football-trainer/index'
import { Route as FootballTrainerTrainerImport } from './routes/football-trainer/trainer'
import { Route as FootballTrainerPairImport } from './routes/football-trainer/pair'

// Create/Update Routes

const FootballTrainerIndexRoute = FootballTrainerIndexImport.update({
  id: '/football-trainer/',
  path: '/football-trainer/',
  getParentRoute: () => rootRoute,
} as any)

const FootballTrainerTrainerRoute = FootballTrainerTrainerImport.update({
  id: '/football-trainer/trainer',
  path: '/football-trainer/trainer',
  getParentRoute: () => rootRoute,
} as any)

const FootballTrainerPairRoute = FootballTrainerPairImport.update({
  id: '/football-trainer/pair',
  path: '/football-trainer/pair',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/football-trainer/pair': {
      id: '/football-trainer/pair'
      path: '/football-trainer/pair'
      fullPath: '/football-trainer/pair'
      preLoaderRoute: typeof FootballTrainerPairImport
      parentRoute: typeof rootRoute
    }
    '/football-trainer/trainer': {
      id: '/football-trainer/trainer'
      path: '/football-trainer/trainer'
      fullPath: '/football-trainer/trainer'
      preLoaderRoute: typeof FootballTrainerTrainerImport
      parentRoute: typeof rootRoute
    }
    '/football-trainer/': {
      id: '/football-trainer/'
      path: '/football-trainer'
      fullPath: '/football-trainer'
      preLoaderRoute: typeof FootballTrainerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/football-trainer/pair': typeof FootballTrainerPairRoute
  '/football-trainer/trainer': typeof FootballTrainerTrainerRoute
  '/football-trainer': typeof FootballTrainerIndexRoute
}

export interface FileRoutesByTo {
  '/football-trainer/pair': typeof FootballTrainerPairRoute
  '/football-trainer/trainer': typeof FootballTrainerTrainerRoute
  '/football-trainer': typeof FootballTrainerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/football-trainer/pair': typeof FootballTrainerPairRoute
  '/football-trainer/trainer': typeof FootballTrainerTrainerRoute
  '/football-trainer/': typeof FootballTrainerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/football-trainer/pair'
    | '/football-trainer/trainer'
    | '/football-trainer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/football-trainer/pair'
    | '/football-trainer/trainer'
    | '/football-trainer'
  id:
    | '__root__'
    | '/football-trainer/pair'
    | '/football-trainer/trainer'
    | '/football-trainer/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  FootballTrainerPairRoute: typeof FootballTrainerPairRoute
  FootballTrainerTrainerRoute: typeof FootballTrainerTrainerRoute
  FootballTrainerIndexRoute: typeof FootballTrainerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  FootballTrainerPairRoute: FootballTrainerPairRoute,
  FootballTrainerTrainerRoute: FootballTrainerTrainerRoute,
  FootballTrainerIndexRoute: FootballTrainerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/football-trainer/pair",
        "/football-trainer/trainer",
        "/football-trainer/"
      ]
    },
    "/football-trainer/pair": {
      "filePath": "football-trainer/pair.tsx"
    },
    "/football-trainer/trainer": {
      "filePath": "football-trainer/trainer.tsx"
    },
    "/football-trainer/": {
      "filePath": "football-trainer/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
