/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FootballTrainerIndexImport } from './routes/football-trainer/index'
import { Route as FootballTrainerPairLeaderImport } from './routes/football-trainer/pair/leader'

// Create/Update Routes

const FootballTrainerIndexRoute = FootballTrainerIndexImport.update({
  id: '/football-trainer/',
  path: '/football-trainer/',
  getParentRoute: () => rootRoute,
} as any)

const FootballTrainerPairLeaderRoute = FootballTrainerPairLeaderImport.update({
  id: '/football-trainer/pair/leader',
  path: '/football-trainer/pair/leader',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/football-trainer/': {
      id: '/football-trainer/'
      path: '/football-trainer'
      fullPath: '/football-trainer'
      preLoaderRoute: typeof FootballTrainerIndexImport
      parentRoute: typeof rootRoute
    }
    '/football-trainer/pair/leader': {
      id: '/football-trainer/pair/leader'
      path: '/football-trainer/pair/leader'
      fullPath: '/football-trainer/pair/leader'
      preLoaderRoute: typeof FootballTrainerPairLeaderImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/football-trainer': typeof FootballTrainerIndexRoute
  '/football-trainer/pair/leader': typeof FootballTrainerPairLeaderRoute
}

export interface FileRoutesByTo {
  '/football-trainer': typeof FootballTrainerIndexRoute
  '/football-trainer/pair/leader': typeof FootballTrainerPairLeaderRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/football-trainer/': typeof FootballTrainerIndexRoute
  '/football-trainer/pair/leader': typeof FootballTrainerPairLeaderRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/football-trainer' | '/football-trainer/pair/leader'
  fileRoutesByTo: FileRoutesByTo
  to: '/football-trainer' | '/football-trainer/pair/leader'
  id: '__root__' | '/football-trainer/' | '/football-trainer/pair/leader'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  FootballTrainerIndexRoute: typeof FootballTrainerIndexRoute
  FootballTrainerPairLeaderRoute: typeof FootballTrainerPairLeaderRoute
}

const rootRouteChildren: RootRouteChildren = {
  FootballTrainerIndexRoute: FootballTrainerIndexRoute,
  FootballTrainerPairLeaderRoute: FootballTrainerPairLeaderRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/football-trainer/",
        "/football-trainer/pair/leader"
      ]
    },
    "/football-trainer/": {
      "filePath": "football-trainer/index.tsx"
    },
    "/football-trainer/pair/leader": {
      "filePath": "football-trainer/pair/leader.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
